name: university
description: Open Source app to find Free resources online.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_swiper_null_safety: ^1.0.2
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  provider: ^6.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  image_path: "assets/images/logo.jpeg"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
